### ISSUE TITLE
Partial block that contains a comment renders incorrectly

### ISSUE THREAD

**Issue by lougreenwood** [zordius/lightncandy#224]
Hello,

I have the following template `test.hbs`

```
<section class="c-section-primary  js-hook__section--primary"  data-secondary-nav-title="{{{title}}}">

	{{> @partial-block this }}

</section>
```

`index.hbs` contains the following:

```
{{#> _c-test payload }}

	<div>
		<h2>
			{{{title}}}
		</h2>
	        <h3>
			{{{description}}}
		</h3>
	</div>

	<div>
		{{!-- A comment --}}
		{{{title}}}
	</div>

{{/_c-test}}

```

I've noticed that when a comment is included in the second div, the rendered HTML is messed up, I'd expect the following (no comment within partial block):

```
<section class="c-section-primary  js-hook__section--primary" data-secondary-nav-title="A Title">
	<div>
		<h2>
			A Title
		</h2>
		<h3>
			A Description
		</h3>
	</div>

	<div>
		Some Content
	</div>
</section>
```

Instead, when comments are included, I get:

```
<section>
	<div>
		<h2>
			A Title
		</h2>
		<h3>
			A Description
			Some Content
		</h3>
	</div>
</section>
```

Notice that the content is wrapped in the previous h3 tag and the content's own div has disappeared. This seems to happen consistently, even if the comment is placed elsewhere.

I have the following flags set:
`"flags" => LightnCandy::FLAG_RUNTIMEPARTIAL | LightnCandy::FLAG_THIS | LightnCandy::FLAG_SPVARS | LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_ERROR_SKIPPARTIAL | LightnCandy::FLAG_PARENT`

**Comment by lougreenwood** [comment]
Also, if I render a partial within the partial block, comments don't seem to cause any issues.

**Comment by lougreenwood** [comment]
I've also just noticed that if an if/else statement is in the partial, I get an error... not sure if that's related in any way...

**Comment by ymeiner** [comment]
We have the same thing with if/else expression.

**Comment by zordius** [comment]
Hello, I just add <a href="https://github.com/zordius/lightncandy/commit/568832d01b61510083a5d8ca050605cdef4239d6">2 test cases</a> for this issue but everything works fine. Please provide more hints to identify this issue, thanks.

**Comment by zordius** [comment]
Sorry, I just saw a strange issue here: https://github.com/zordius/lightncandy/commit/568832d01b61510083a5d8ca050605cdef4239d6#diff-57c6895bc9d5d022a2c0fa50f62c3306R1060 , will try to fix the if/else issue.

**Comment by zordius** [comment]
Sorry again. the `{{else}}` only works with `LightnCandy::FLAG_ELSE` , so the 2 new tests works as expect.

**Comment by lougreenwood** [comment]
Here's a PHP example which demonstrates the bug:

```
<?php 
require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
<body>
    <p>inside page body</p>
    {{#> test_modal}}
      <div style="background-color: blue; width: 100%;"> Modal header</div>
      <div style="border: 1px solid black; width: 100%;">
        {{!-- some comment --}}
        <p>inside modal partial block</p>
        {{> test_form_body}}
      </div>
      <div style="background-color: pink; width: 100%;">Modal Footer</div>
    {{/test_modal}}
</body>
VAREND;

// Helpers:
$helpers = array(
  'foo' => function () {
    return 'Hello World';
  },
);

// Partials:
$partials = array(
  'test_modal'        => '<div class="some_modal"><p>hello from test_modal</p>{{> @partial-block }}</div>',
  'test_form_wrapper' => '<div class="form_wrapper"><p>hello from test_form_wrapper</p>{{> @partial-block }}</div>',
  'test_form_body'    => '<form action=""><p>hello from test_form_body</p><input type="text"> My input</form>',
);

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_RUNTIMEPARTIAL | LightnCandy::FLAG_THIS | LightnCandy::FLAG_SPVARS | LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_ERROR_SKIPPARTIAL | LightnCandy::FLAG_PARENT | LightnCandy::FLAG_ELSE,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$phpStr\n";

// Input Data:
$data = array(
  'qoo' => 'moo'
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
?>
```

Rendered result (with comment) =
![screen shot 2016-07-23 at 14 12 45](https://cloud.githubusercontent.com/assets/12051736/17078020/929423ca-50df-11e6-9afa-e53e7416aad5.png)

If you remove the {{!-- some comment --}} line you'll see that the page renders correctly (as shown below)
![screen shot 2016-07-23 at 14 13 30](https://cloud.githubusercontent.com/assets/12051736/17078024/a8143032-50df-11e6-8c70-ea5b328b08e0.png)


And if you move the position of the comment to here:

```
$template = <<<VAREND
<body>
    <p>inside page body</p>
    {{#> test_modal}}
      <div style="background-color: blue; width: 100%;"> Modal header</div>
      <div style="border: 1px solid black; width: 100%;">
        
        <p>inside modal partial block</p>
        {{> test_form_body}}
      </div>
      {{!-- some comment --}}
      <div style="background-color: pink; width: 100%;">Modal Footer</div>
    {{/test_modal}}
</body>
VAREND;
```

You'll see that the rendered output goes even crazier (border around debug info):
![screen shot 2016-07-23 at 14 15 03](https://cloud.githubusercontent.com/assets/12051736/17078040/e52ed59e-50df-11e6-8f8c-bb530cffb7e4.png)

Thanks :)

**Comment by zordius** [comment]
Thank you for your sample! I found a bug about "string before the comment will be drop when in partial block" , will fix it soon.

**Comment by zordius** [comment]
it should be fixed, please try current master, thanks!

**Comment by lougreenwood** [comment]
@zordius Hey - re-opening this as I'm still getting weird issues using {{if}}{{else}}{{/if}}.

e.g, this code block gives me an error:

**Block**
```
{{#each completion_criteria.body}}
	<span class="{{#if completed_flag}}u-colorize-text--positive{{else}}u-colorize-text--negative{{/if}}">
		{{#if completed_flag}}
			<i class="fa fa-fw fa-check" aria-hidden="true"></i>
			{{else}}
			<i class="fa fa-fw fa-times" aria-hidden="true"></i>
		{{/if}}
		{{{label}}}
	</span>
{{/each}}
```

**Error**
```
Exception
{{else}} only valid in if, unless, each, and #section context
```

My only work around is to an `if` & a separate `unless` to check the inverse.

**Comment by zordius** [comment]
Tests with this sample code on lightncandy current version ( v1.2.0 ) without any error.

```php
<?php

require('./vendor/autoload.php');
use LightnCandy\LightnCandy;

// The Template:
$template = <<<VAREND
{{#each completion_criteria.body}}
  <span class="{{#if completed_flag}}u-colorize-text--positive{{else}}u-colorize-text--negative{{/if}}">
    {{#if completed_flag}}
      <i class="fa fa-fw fa-check" aria-hidden="true"></i>
    {{else}}
      <i class="fa fa-fw fa-times" aria-hidden="true"></i>
    {{/if}}
    {{{label}}}
  </span>
{{/each}}
VAREND;

// Helpers:
$helpers = array();

// Partials:
$partials = array();

$phpStr = LightnCandy::compile($template, array(
  // Used compile flags
  'flags' => LightnCandy::FLAG_ERROR_EXCEPTION | LightnCandy::FLAG_HANDLEBARS,
  'helpers' => $helpers,
  'partials' => $partials,
));

echo "Generated PHP Code:\n$phpStr\n";

// Input Data:
$data = array(
  'set_to_iterate' => array(
    array('name_enabled' => 0, 'name' => 'ItemOne'),
    array('name_enabled' => 1, 'name' => 'ItemTwo'),
    array('name_enabled' => false, 'name' => 'ItemThree'),
    array('name_enabled' => TRUE, 'name' => 'ItemFour'),
  )
);

// Save the compiled PHP code into a php file
file_put_contents('render.php', '<?php ' . $phpStr . '?>');

// Get the render function from the php file
$renderer = include('render.php');

echo "Result:\n" . $renderer($data);
```
